### ISSUE TITLE
Multiple collision bug in last level

### ISSUE THREAD

**Issue by vlasec** [szimek/impasse-js#15]
Steps to reproduce: In last level: Up, Right, Right

Expected behavior: The player dies due to collision with blue arrow

Actual behavior: The player survives. It seems that only the collision with green dot is evaluated upon entering.

**Comment by szimek** [comment]
Hey @vlasec! I released it 10 years ago and you're the first person who found a bug in it. Congrats! :)

I know why it's happening - the green ones are treated differently and the assumption was, that there's always at most 1 colliding block, which is not the case here.

I haven't touched it in ages, but I'll try to fix it :) Thanks again!

**Comment by vlasec** [comment]
I was surprised that you already did it such a long time ago, as Flash was still working back then, and its deprecation took quite some time to take full effect.

Anyway, you did a great job. It would be a pity if the game could only be played in some very exotic software, I think it's one of the best puzzle games I've ever played on Kongregate.
